## Numpy array and basics

In [2]:
import numpy as np

## creating arrays

In [3]:
array1d=np.array([1,2,3])
print(array1d)

array2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array2d)

[1 2 3]
[[1 2 3 4]
 [5 6 7 8]]


## array multipllication

In [4]:
list=[1,2,3,4]
print("multiplication of 1d matrix : ",list*2)
print("multiplication of rd matrix : ",array1d*2)

multiplication of 1d matrix :  [1, 2, 3, 4, 1, 2, 3, 4]
multiplication of rd matrix :  [2 4 6]


### 1->list multiplication is making same list multiple times , but array multiplication is like matrices

### 2-> making diffrent arrays from scratch

In [5]:
ones=np.ones((3,3))#this gonna make the matrices of one only , with provided order
print(ones)

zeros=np.zeros((2,3))
print("the ,atrix with full elements is :",zeros)

full=np.full((2,2),8)#first order of the matrix then the only elemnt of the matrix
print("the matrix with any elemnt is :", full)


random=np.random.random((2,3))# to have access to random amount
print("random array :",random)

sequence=np.arange(0,10,2)#array in sequence , start ,stop ,and the intervals
print("sequence array : ",sequence)






[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
the ,atrix with full elements is : [[0. 0. 0.]
 [0. 0. 0.]]
the matrix with any elemnt is : [[8 8]
 [8 8]]
random array : [[0.58933589 0.46775133 0.33708282]
 [0.63479791 0.52435382 0.19557558]]
sequence array :  [0 2 4 6 8]


## vector , Matrix and Tensors
### 1. vector-> Vector is a one dimensional array , which means a single array.
### 2. Matrix-> Matrix is a array inside another array , something like 2 dimensions
### 3. Tenssors-> Tensors are the arrays which have more dimenisons then matrix
 


In [6]:
vector=np.array([1,2,3,4])
print("vecotr:",vector)
matrix=np.array([[1,2,3],
                [4,5,6]])
print("matrix :", matrix)

tensors=np.array([[[1,2,3,2],[3,4,6,5]],
                  [[6,7,5,8],[9,5,6,3]]])
print("tensior : ", tensors)


vecotr: [1 2 3 4]
matrix : [[1 2 3]
 [4 5 6]]
tensior :  [[[1 2 3 2]
  [3 4 6 5]]

 [[6 7 5 8]
  [9 5 6 3]]]


### arrays properties

In [7]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("size : ",arr.size)# no of the elements

print("dimension :", arr.ndim)#the dimension of the array
print("shape",arr.shape)#the order of the matrix , in rows and column
print("DType : ",arr.dtype)# the data type

size :  6
dimension : 2
shape (2, 3)
DType :  int64


## array reshaping

In [ ]:
arr=np.arange(12)

print("original array :",arr)

reshaped=arr.reshape((3,4))
print("reshaped array : ",reshaped)

flattened=reshaped.flatten()
print("flate array : ",flattened)

#transpose
transpose=reshaped.T
print("the trasposed matrix is :",transpose)



original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flate array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
the trasposed matrix is : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
