# Practice Numpy Library
## Basic Level
* ### Array Creation And Properties
1. Create a 1D NumPy array of integers from 10 to 49.

2. Create a 3×3 matrix with values ranging from 0 to 8.

3. Create a 4×4 identity matrix.

4. Generate a 5×5 matrix filled with random floats in the range [0, 1).

5. Find the shape, dtype, ndim, and size of a given array.

In [17]:
import numpy as np

In [32]:
# creating  1D NumPy array of integers from 10 to 49
arr1=np.arange(10,50)
print("The first array is ",arr1)

#creating 3×3 matrix with values ranging from 0 to 8.
arr2=np.arange(0,9).reshape(3,3)
print("the second array is : ",arr2)
#Create a 4×4 identity matrix.
arr3=np.identity(4)
print("The third matrix is :",arr3)
# Creating a a 5×5 matrix filled with random floats in the range [0, 1).
arr4=np.random.random((5,5))
print("The fourth matrix is :",arr4)
#Finding the shape, dtype, ndim, and size of a given array.
print("The ahpe of the given array is : ",arr4.shape)
print("The datatype of the array is :",arr4.dtype)
print("The dimension of the array is :",arr4.ndim)
print("The size of the array is :",arr1.size)



The first array is  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
the second array is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
The third matrix is : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The fourth matrix is : [[0.72916602 0.57927949 0.13782492 0.42527325 0.11132923]
 [0.78104193 0.95112137 0.51027026 0.41332258 0.42362415]
 [0.15940392 0.20829159 0.33320028 0.67263001 0.12550532]
 [0.95735474 0.93173697 0.74713273 0.99916354 0.28393883]
 [0.04407524 0.57553769 0.32093819 0.12620172 0.10050911]]
The ahpe of the given array is :  (5, 5)
The datatype of the array is : float64
The dimension of the array is : 2
The size of the array is : 40


* ### Indexing and sclicing
1. Given a 1D array, extract:
> 1. The first 3 elements
> 2. The last 3 elements
> 3. Every alternate element

2. From a 5×5 matrix, extract:

> 1. The central 3×3 sub-matrix
> 2. The first row and last column

3. Replace all even numbers in an array with 0.

In [38]:
print("First three element of the array :",arr1[0:3])
print("Last Three elements : ",arr1[-4:-1])
print("The alternative elemen in the array is :",arr1[0:41:2])

First three element of the array : [10 11 12]
Last Three elements :  [46 47 48]
The alternative elemen in the array is : [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
