# Practice Numpy Library
## Basic Level
* ### Array Creation And Properties
1. Create a 1D NumPy array of integers from 10 to 49.

2. Create a 3×3 matrix with values ranging from 0 to 8.

3. Create a 4×4 identity matrix.

4. Generate a 5×5 matrix filled with random floats in the range [0, 1).

5. Find the shape, dtype, ndim, and size of a given array.

In [6]:
import numpy as np

In [ ]:
# creating  1D NumPy array of integers from 10 to 49
arr1=np.arange(10,50)
print("The first array is ",arr1)

#creating 3×3 matrix with values ranging from 0 to 8.
arr2=np.arange(0,9).reshape(3,3)
print("the second array is : ",arr2)
#Create a 4×4 identity matrix.
arr3=np.identity(4)
print("The third matrix is :",arr3)
# Creating a a 5×5 matrix filled with random floats in the range [0, 1).
arr4=np.random.random((5,5))
print("The fourth matrix is :",arr4)



The first array is  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
the second array is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
The third matrix is : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.6644579  0.05575132 0.52058751 0.10466002 0.75218465]
 [0.08113563 0.15020604 0.90572838 0.13769634 0.59132599]
 [0.45616823 0.58129748 0.25093841 0.44832668 0.68078419]
 [0.20766139 0.1443293  0.23453138 0.29444259 0.65954397]
 [0.80679064 0.22447461 0.98234543 0.02519528 0.94777629]]
