# Practice Numpy Library
## Basic Level
* ### Array Creation And Properties
1. Create a 1D NumPy array of integers from 10 to 49.

2. Create a 3×3 matrix with values ranging from 0 to 8.

3. Create a 4×4 identity matrix.

4. Generate a 5×5 matrix filled with random floats in the range [0, 1).

5. Find the shape, dtype, ndim, and size of a given array.

In [59]:
import numpy as np

In [60]:
# creating  1D NumPy array of integers from 10 to 49
arr1=np.arange(10,50)
print("The first array is ",arr1)

#creating 3×3 matrix with values ranging from 0 to 8.
arr2=np.arange(0,9).reshape(3,3)
print("the second array is : ",arr2)
#Create a 4×4 identity matrix.
arr3=np.identity(4)
print("The third matrix is :",arr3)
# Creating a a 5×5 matrix filled with random floats in the range [0, 1).
arr4=np.random.random((5,5))
print("The fourth matrix is :",arr4)
#Finding the shape, dtype, ndim, and size of a given array.
print("The ahpe of the given array is : ",arr4.shape)
print("The datatype of the array is :",arr4.dtype)
print("The dimension of the array is :",arr4.ndim)
print("The size of the array is :",arr1.size)



The first array is  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
the second array is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
The third matrix is : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The fourth matrix is : [[0.18236753 0.30781212 0.90206467 0.69947825 0.94077538]
 [0.65345746 0.36796618 0.20835375 0.42172374 0.73297859]
 [0.9471001  0.73311815 0.31959239 0.90585113 0.86748743]
 [0.65765147 0.06057921 0.30777873 0.02933859 0.60871119]
 [0.83158459 0.29983819 0.82343986 0.89778603 0.19243791]]
The ahpe of the given array is :  (5, 5)
The datatype of the array is : float64
The dimension of the array is : 2
The size of the array is : 40


* ### Indexing and slicing
1. Given a 1D array, extract:
> 1. The first 3 elements
> 2. The last 3 elements
> 3. Every alternate element

2. From a 5×5 matrix, extract:

> 1. The central 3×3 sub-matrix
> 2. The first row and last column

3. Replace all even numbers in an array with 0.

In [61]:
print("First three element of the array :",arr1[0:3])
print("Last Three elements : ",arr1[-4:-1])
print("The alternative elemen in the array is :",arr1[0:41:2])

First three element of the array : [10 11 12]
Last Three elements :  [46 47 48]
The alternative elemen in the array is : [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [62]:
print("The submatrix 3x3 from a 5 order maatrix : ",arr4[1:4,1:4])
print("First row and last column :",arr4[1,:],arr4[:,4])

The submatrix 3x3 from a 5 order maatrix :  [[0.36796618 0.20835375 0.42172374]
 [0.73311815 0.31959239 0.90585113]
 [0.06057921 0.30777873 0.02933859]]
First row and last column : [0.65345746 0.36796618 0.20835375 0.42172374 0.73297859] [0.94077538 0.73297859 0.86748743 0.60871119 0.19243791]


In [ ]:
wh=np.where(arr2%2==0,0,arr2) 
print(wh)


[[0 1 0]
 [3 0 5]
 [0 7 0]]
