# Practice Numpy Library
## Basic Level
* ### Array Creation And Properties
1. Create a 1D NumPy array of integers from 10 to 49.

2. Create a 3×3 matrix with values ranging from 0 to 8.

3. Create a 4×4 identity matrix.

4. Generate a 5×5 matrix filled with random floats in the range [0, 1).

5. Find the shape, dtype, ndim, and size of a given array.

In [6]:
import numpy as np

In [16]:
# creating  1D NumPy array of integers from 10 to 49
arr1=np.arange(10,50)
print("The first array is ",arr1)

#creating 3×3 matrix with values ranging from 0 to 8.
arr2=np.arange(0,9).reshape(3,3)
print("the second array is : ",arr2)
#Create a 4×4 identity matrix.
arr3=np.identity(4)
print("The third matrix is :",arr3)
# Creating a a 5×5 matrix filled with random floats in the range [0, 1).
arr4=np.random.random((5,5))
print("The fourth matrix is :",arr4)
#Finding the shape, dtype, ndim, and size of a given array.
print("The ahpe of the given array is : ",arr4.shape)
print("The datatype of the array is :",arr4.dtype)
print("The dimension of the array is :",arr4.ndim)
print("The size of the array is :",arr4.size)



The first array is  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
the second array is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
The third matrix is : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The fourth matrix is : [[0.08282642 0.14223825 0.80332509 0.91251234 0.6492338 ]
 [0.50118438 0.19671552 0.3157262  0.45082032 0.43048514]
 [0.794973   0.17833287 0.42132108 0.01933557 0.06664544]
 [0.09591194 0.46687715 0.84987564 0.68622051 0.80048177]
 [0.88898015 0.38608395 0.2327563  0.20034995 0.09555394]]
The ahpe of the given array is :  (5, 5)
The datatype of the array is : float64
The dimension of the array is : 2
The size of the array is : 25
