# Practice Numpy Library
## Moderate Practice
1. Broadcasting & Vectorization

    1. Subtract the mean of each column from a 2D matrix without using loops.
    2. Multiply each row of a matrix by a different scalar.

In [2]:
import numpy as np

In [3]:
#Subtract the mean of each column from a 2D matrix without using loops.
arr=np.arange(0,4).reshape(2,2)
arr= arr-arr[:,1].mean()-arr[:,0].mean()

print(arr)
#Multiply each row of a matrix by a different scalar.
arr[1]=arr[1]*2
arr[0]=arr[0]*5
print("the array after multipling it's row by scalar value:",arr)

[[-3. -2.]
 [-1.  0.]]
the array after multipling it's row by scalar value: [[-15. -10.]
 [ -2.   0.]]


2. Linear Algebra
    1. Compute :
        1. Matrix transpose
        2. Matrix inverse
        3. Determinant
    
    2. Solve a system of linear equations using NumPy.
    3. Verify the matrix multiplication rule: (AB)^T=(B^T)(A^T)

In [4]:
print("The transpose of the matrix is :",arr.transpose())
print("The determinant of the matrix is : ",np.linalg.det(arr))
print("The inverse of the matrix :",np.linalg.inv(arr))

The transpose of the matrix is : [[-15.  -2.]
 [-10.   0.]]
The determinant of the matrix is :  -19.999999999999996
The inverse of the matrix : [[ 3.70074342e-18 -5.00000000e-01]
 [-1.00000000e-01  7.50000000e-01]]


> The system of eqaution to solve :
1. ​2x+y−z=1
2. −3x−y+2z=−4
3. −2x+y+2z=−1​

In [5]:
#let
a=np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
b=np.array([1,-4,-1])

ans=np.linalg.solve(a,b)
print("x=",ans[0])
print("y=",ans[1])
print("z=",ans[2])

x= -7.000000000000003
y= 5.000000000000002
z= -10.000000000000002


In [6]:
A=np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
B=np.array([[4,5,6],[8,9,7],[3,5,4]])
AB=np.dot(A,B).T
A_Trans=A.T
B_Trans=B.T
prod2=np.dot(B_Trans,A_Trans)
if AB.all()==prod2.all():
    print("Hence Proved!!")
else:
    print("Error")

Hence Proved!!


3. Statistical & Aggregation Operations :
    1. Compute column-wise and row-wise:
        1. Mean
        2. Median
        3. Sum

    2. Find the index of:
        1. Maximum value in each row
        2. Minimum value in each column

In [14]:
arr=np.array([[4,5,6],[8,9,7],[3,5,4]])
print("mean of first row of the matrix : ",arr[0].mean())
print("Mean fo first column : ",arr[:,0].mean())
print("Summition of first row of the matrix is ",arr[0].sum())
print("Summation of first column of the matrix : ",arr[:,0].sum())

mean of first row of the matrix :  5.0
Mean fo first column :  5.0
Summition of first row of the matrix is  15
Summation of first column of the matrix :  15


In [20]:
max=arr[0].max()
print("The maximum of first row of the matrix : ",np.where(arr==max))
print("The minimum value of first column : ",np.where(arr==arr[0].min()))

The maximum of first row of the matrix :  (array([0]), array([2]))
The minimum value of first column :  (array([0, 2]), array([0, 2]))


4. Reshaping & Stacking

    1. Reshape a 1D array of size 24 into a 3D array.

    2. Stack two arrays:
       1. Vertically
       2. Horizontally

    3. Split an array into equal-sized chunks.

In [ ]:
arr=np.arange(0,24).reshape(2,3,4)
print(arr)

arr2=np.array([[1,2,3],[4,5,6]])
a1=np.array([7,8,9])

a2=np.array([[1],[2]])

b=np.vstack((arr2,a1))
c=np.hstack((arr2,a2))

print(b)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1]
 [4 5 6 2]]


In [41]:
arr=np.arange(8)
sp=np.split(arr,2)
print(sp)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
