## numpyy array operation

In [2]:
import numpy as np

In [32]:
arr =np.arange(1,10)
print("original aray : ",arr)
print("sliced array : ",arr[2:8])
print("slicing with step : ",arr[2:8:2])
print("negitive indexing :",arr[-1])
      

original aray :  [1 2 3 4 5 6 7 8 9]
sliced array :  [3 4 5 6 7 8]
slicing with step :  [3 5 7]
negitive indexing : 9


## Indexing in 2d array

In [33]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,1,2,3]])
print("specific element : ",arr[1,3])
print("entire row : ",arr[1])
print("entire column : ",arr[:,3])


specific element :  8
entire row :  [5 6 7 8]
entire column :  [4 8 3]


## sorting


In [34]:
narr=np.array([4,3,2,6,5,3,2,8,0])
print("unsorted array : ",narr)
sarr=np.sort(narr)
print("sorted array :",sarr)

unsorted array :  [4 3 2 6 5 3 2 8 0]
sorted array : [0 2 2 3 3 4 5 6 8]


In [35]:
narr_2d=np.array([[1,2,],[3,2],[1,3]])

print("unsorted 2dd array : ",narr_2d)

print("sorted by columen at axis =0 : ",np.sort(narr_2d,axis=0))
print("sorted by row at axis =1 : ", np.sort(narr_2d,axis=1))




unsorted 2dd array :  [[1 2]
 [3 2]
 [1 3]]
sorted by columen at axis =0 :  [[1 2]
 [1 2]
 [3 3]]
sorted by row at axis =1 :  [[1 2]
 [2 3]
 [1 3]]


## Filter


In [36]:
numbers=np.arange(1,11)
even=numbers[numbers % 2 ==0]
print("even Numbber :",even)
#we can putcondition here as well  

even Numbber : [ 2  4  6  8 10]


In [37]:
mask=numbers>5
print(numbers[mask])


[ 6  7  8  9 10]


## indexing VS where indexing

In [38]:
indices=[0,2,4]
print(numbers[indices])# this gonna print the the  number in the numbers array ta the index of the indices array 

where_result=np.where(numbers>5)#where_result will  store the index of the elemnt which satistfy the condition
print("the array with the specified index is : ", numbers[where_result])


[1 3 5]
the array with the specified index is :  [ 6  7  8  9 10]


## condtiion using the where 
- * where(if condition , (what to do if true),(what to do if false))
- * in this system this stored the whole array with applied condition

In [39]:
condition_array=np.where(numbers>5,numbers*3,numbers)

print("the modified aray witht the applied condition : ", condition_array)


the modified aray witht the applied condition :  [ 1  2  3  4  5 18 21 24 27 30]


## adding and removing data

In [40]:
arr1 =np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))#  used to combine the arrays 
print('the combined array : ',combined)


the combined array :  [1 2 3 4 5 6]


### array compaitblity

In [41]:
# first compatiblity check is that shape should be same

# as in matrices as well the shape sma ein many operation is important
a=np.array([1,2,3])
b=np.array([4,5,6])
print("compatiblity check : ",a.shape==b.shape)


compatiblity check :  True


In [42]:
original =np.array([[1,2],[3,4]])
new_row=[4,3]

with_new_row=np.vstack((original,new_row))
print(with_new_row)

new_column=[[3],[7]]
with_new_column=np.hstack((original,new_column))
print(with_new_column)

[[1 2]
 [3 4]
 [4 3]]
[[1 2 3]
 [3 4 7]]


In [43]:
delarr=np.array([4,6,3,8])

delete=np.delete(delarr,2)#this will store the array without the eelement , which was deleted
print(delete)


[4 6 8]
